'use strict';(function(){var cmpFile='noModule'in HTMLScriptElement.prototype?'cmp2.js':'cmp2-polyfilled.js';(function(){var cmpScriptElement=document.createElement('script');var firstScript=document.getElementsByTagName('script')[0];cmpScriptElement.async=true;cmpScriptElement.type='text/javascript';var cmpUrl;var tagUrl=document.currentScript.src;cmpUrl='https://cmp.inmobi.com/tcfv2/53/CMP_FILE?referer=cults3d.com'.replace('CMP_FILE',cmpFile);cmpScriptElement.src=cmpUrl;firstScript.parentNode.insertBefore(cmpScriptElement,firstScript);})();(function(){var css=""
+" .qc-cmp-button { "
+"   background-color: #822ef5 !important; "
+"   border-color: #822ef5 !important; "
+" } "
+" .qc-cmp-button:hover { "
+"   border-color: #822ef5 !important; "
+" } "
+" .qc-cmp-alt-action, "
+" .qc-cmp-link { "
+"   color: #822ef5 !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button:hover { "
+"   background-color: #822ef5 !important; "
+"   border-color: #822ef5 !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button:hover { "
+"   color: #ffffff !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button { "
+"   color: #822ef5 !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button { "
+"   background-color: #eee !important; "
+"   border-color: transparent !important; "
+" } "
+" .qc-cmp-ui a, "
+" .qc-cmp-ui .qc-cmp-alt-action { "
+"   color: #822ef5 !important; "
+" } "
+" .qc-cmp-small-toggle.qc-cmp-toggle-on, "
+" .qc-cmp-toggle.qc-cmp-toggle-on { "
+"   background-color: #822ef5!important; "
+"   border-color: #822ef5!important; "
+" } "
+""
+"";var stylesElement=document.createElement('style');var re=new RegExp('&quote;','g');css=css.replace(re,'"');stylesElement.type='text/css';if(stylesElement.styleSheet){stylesElement.styleSheet.cssText=css;}else{stylesElement.appendChild(document.createTextNode(css));}
var head=document.head||document.getElementsByTagName('head')[0];head.appendChild(stylesElement);})();var autoDetectedLanguage='en';var gvlVersion=3;function splitLang(lang){if(lang.includes('pt')&&lang.length>2){return lang.split('-')[0]+'-'+lang.split('-')[1].toLowerCase();}
return lang.length>2?lang.split('-')[0]:lang;};function isSupported(lang){var langs=['en','fr','de','it','es','da','nl','el','hu','pt','pt-br','pt-pt','ro','fi','pl','sk','sv','no','ru','bg','ca','cs','et','hr','lt','lv','mt','sl','tr','uk','zh','id','ko','ja','hi','vi','th','ms'];return langs.indexOf(lang)===-1?false:true;};if(gvlVersion===2&&isSupported(splitLang(document.documentElement.lang))){autoDetectedLanguage=splitLang(document.documentElement.lang);}else if(gvlVersion===3&&isSupported(document.documentElement.lang)){autoDetectedLanguage=document.documentElement.lang;}else if(isSupported(splitLang(navigator.language))){autoDetectedLanguage=splitLang(navigator.language);};var choiceMilliSeconds=(new Date).getTime();window.__tcfapi('init',2,function(){},{"coreConfig":{"siteUuid":"ddb29d29-75b0-4b24-b4b1-a93b8aa77f2e","themeUuid":"3ad11c61-7fa3-49b8-a67a-10d15c64ed3f","inmobiAccountId":"76VRU1L2EJk2N","privacyMode":["GDPR"],"includeVendorsDisclosedSegment":false,"cmpVersion":"53","hashCode":"7llcNfBwv4I9Ku9sU50T2g","publisherCountryCode":"FR","publisherName":"Cults","vendorPurposeIds":[1,2,3,4,5,6,7,8,9,10,11],"vendorFeaturesIds":[1,2,3],"vendorPurposeLegitimateInterestIds":[7,8,9,2,10,11],"vendorSpecialFeaturesIds":[1,2],"vendorSpecialPurposesIds":[1,2,3],"googleEnabled":true,"consentScope":"service","thirdPartyStorageType":"iframe","consentOnSafari":false,"displayUi":"inEU","defaultToggleValue":"off","initScreenRejectButtonShowing":true,"initScreenCloseButtonShowing":false,"softOptInEnabled":false,"showSummaryView":true,"persistentConsentLinkLocation":3,"displayPersistentConsentLink":false,"uiLayout":"banner","publisherLogo":"https://assets.cults3d.com/assets/logos/cults-3d-horizontal-ed3fa3c038d8239752bfb4b0b0e549d1efbe23a59affab618ea4a420f6df6042.svg?qc-size=300,109","vendorListUpdateFreq":365,"publisherPurposeIds":[],"initScreenBodyTextOption":1,"publisherConsentRestrictionIds":[],"publisherLIRestrictionIds":[],"publisherPurposeLegitimateInterestIds":[],"publisherSpecialPurposesIds":[],"publisherFeaturesIds":[],"publisherSpecialFeaturesIds":[],"stacks":[],"lang_":autoDetectedLanguage,"supportedLanguages":["bg","cs","da","de","el","en","es","et","fi","fr","hr","hu","it","lt","lv","mt","nl","no","pl","pt-br","pt-pt","ro","ru","sk","sl","sv","uk","tr","ja","id","ko","zh","hi","vi","th","ms"],"gvlVersion":3,"totalVendors":914,"legitimateInterestOptIn":true,"features":{"visitEvents":true},"translationUrls":{"common":"https://cmp.inmobi.com/tcfv2/translations/${language}.json","theme":"https://cmp.inmobi.com/custom-translations/76VRU1L2EJk2N/3ad11c61-7fa3-49b8-a67a-10d15c64ed3f/${language}.json","all":"https://cmp.inmobi.com/consolidated-translations/76VRU1L2EJk2N/3ad11c61-7fa3-49b8-a67a-10d15c64ed3f/${language}.json"},"gdprEnabledInUS":false},"premiumUiLabels":{},"premiumProperties":{"googleWhitelist":[1]},"coreUiLabels":{},"theme":{"uxPrimaryButtonColor":"#822ef5","uxSecondaryButtonTextColor":"#822ef5","uxToogleActiveColor":"#822ef5","uxLinkColor":"#822ef5"},"nonIabVendorsInfo":{}});})();